version: "3.9"
services:
  server-graphql:
    container_name: server-graphql
    image: api-graphql
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - "databasegraphql"
  databasegraphql:
    container_name: db-graphql
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eduardo
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27018:27017"
  web:
    container_name: client-graphql
    image: nginx:latest
    ports:
      - "4004:80"
    command: "nginx -g 'daemon off;'"          
    volumes:
      - ./client:/usr/share/nginx/html
